"""0001 baseline telemetry schema

Revision ID: 3a1bc4fecef2
Revises: 
Create Date: 2026-05-08 10:59:23.921132
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '3a1bc4fecef2'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=False),
    sa.Column('actor_role', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_kind', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=255), nullable=False),
    sa.Column('payload_hash', sa.String(length=128), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('prev_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_actor', 'audit_entries', ['actor_id'], unique=False)
    op.create_index('idx_audit_at', 'audit_entries', ['at'], unique=False)
    op.create_index('idx_audit_target', 'audit_entries', ['target_kind', 'target_id'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('retention_policy', sa.JSON(), nullable=False),
    sa.Column('iso_37120_default', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('ouvidoria_oficial','social_publica','formulario_interno')", name='ck_sources_kind'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_enabled'), 'sources', ['enabled'], unique=False)
    op.create_index(op.f('ix_sources_kind'), 'sources', ['kind'], unique=False)
    op.create_index(op.f('ix_sources_slug'), 'sources', ['slug'], unique=True)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('events_collected', sa.Integer(), nullable=False),
    sa.Column('events_quarantined', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.String(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.CheckConstraint("status IN ('running','succeeded','partial','failed')", name='ck_pipeline_runs_status'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pipeline_runs_source_started', 'pipeline_runs', ['source_id', 'started_at'], unique=False)
    op.create_table('telemetry_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('region_code', sa.String(length=7), nullable=False),
    sa.Column('unit_code', sa.String(length=32), nullable=True),
    sa.Column('topic', sa.String(length=64), nullable=False),
    sa.Column('subtopic', sa.String(length=64), nullable=True),
    sa.Column('sentiment', sa.SmallInteger(), nullable=False),
    sa.Column('severity', sa.SmallInteger(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('text_anonymized', sa.String(), nullable=False),
    sa.Column('pii_tokens', sa.JSON(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('iso_37120', sa.JSON(), nullable=False),
    sa.Column('iso_37122', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('classified','quarantined','reprocessing')", name='ck_events_status'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_events_confidence'),
    sa.CheckConstraint('sentiment >= -2 AND sentiment <= 2', name='ck_events_sentiment'),
    sa.CheckConstraint('severity >= 0 AND severity <= 3', name='ck_events_severity'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_events_source_external')
    )
    op.create_index('idx_events_region', 'telemetry_events', ['region_code'], unique=False)
    op.create_index('idx_events_source_received', 'telemetry_events', ['source_id', 'received_at'], unique=False)
    op.create_index('idx_events_topic_received', 'telemetry_events', ['topic', 'received_at'], unique=False)
    op.create_index(op.f('ix_telemetry_events_status'), 'telemetry_events', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_events_status'), table_name='telemetry_events')
    op.drop_index('idx_events_topic_received', table_name='telemetry_events')
    op.drop_index('idx_events_source_received', table_name='telemetry_events')
    op.drop_index('idx_events_region', table_name='telemetry_events')
    op.drop_table('telemetry_events')
    op.drop_index('idx_pipeline_runs_source_started', table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_sources_slug'), table_name='sources')
    op.drop_index(op.f('ix_sources_kind'), table_name='sources')
    op.drop_index(op.f('ix_sources_enabled'), table_name='sources')
    op.drop_table('sources')
    op.drop_index('idx_audit_target', table_name='audit_entries')
    op.drop_index('idx_audit_at', table_name='audit_entries')
    op.drop_index('idx_audit_actor', table_name='audit_entries')
    op.drop_table('audit_entries')
    # ### end Alembic commands ###
