"""0003 ai workers tables

Revision ID: 7b3d58dfb2c6
Revises: bb688fa367e5
Create Date: 2026-05-15 08:05:27.824232
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '7b3d58dfb2c6'
down_revision: str | None = 'bb688fa367e5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_anomaly_signals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scope_kind', sa.String(length=16), nullable=False),
    sa.Column('scope_value', sa.String(length=64), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('baseline', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('observed', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('deviation_score', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('severity', sa.SmallInteger(), nullable=False),
    sa.Column('evidence_event_ids', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("scope_kind IN ('region','unit','topic','global')", name='ck_anomaly_scope_kind'),
    sa.CheckConstraint("status IN ('open','acknowledged','resolved','false_positive')", name='ck_anomaly_status'),
    sa.CheckConstraint('severity >= 0 AND severity <= 3', name='ck_anomaly_severity'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_anomaly_detected_at', 'ai_anomaly_signals', ['detected_at'], unique=False)
    op.create_index('idx_anomaly_scope', 'ai_anomaly_signals', ['scope_kind', 'scope_value'], unique=False)
    op.create_index('idx_anomaly_status', 'ai_anomaly_signals', ['status'], unique=False)
    op.create_table('ai_daily_briefs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('brief_date', sa.Date(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('top_signal_ids', sa.JSON(), nullable=False),
    sa.Column('pending_recommendation_ids', sa.JSON(), nullable=False),
    sa.Column('kpi_snapshot', sa.JSON(), nullable=False),
    sa.Column('summary_text', sa.String(), nullable=False),
    sa.Column('degraded_mode', sa.Boolean(), nullable=False),
    sa.Column('llm_provider', sa.String(length=64), nullable=True),
    sa.Column('llm_model', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brief_date', name='uq_daily_brief_date')
    )
    op.create_table('ai_worker_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('worker_name', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('input_summary', sa.JSON(), nullable=False),
    sa.Column('output_summary', sa.JSON(), nullable=False),
    sa.Column('llm_provider', sa.String(length=64), nullable=True),
    sa.Column('llm_model', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.CheckConstraint("status IN ('success','degraded','failure')", name='ck_worker_run_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_worker_run_started', 'ai_worker_runs', ['started_at'], unique=False)
    op.create_index('idx_worker_run_worker_status', 'ai_worker_runs', ['worker_name', 'status'], unique=False)
    op.create_table('ai_recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('anomaly_signal_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('proposed_action', sa.String(), nullable=False),
    sa.Column('justification', sa.String(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('llm_provider', sa.String(length=64), nullable=True),
    sa.Column('llm_model', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('hitl_status', sa.String(length=16), nullable=False),
    sa.Column('decided_by', sa.String(length=255), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('edited_action', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("hitl_status IN ('pending','approved','rejected','edited')", name='ck_recommendation_hitl_status'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_recommendation_confidence'),
    sa.ForeignKeyConstraint(['anomaly_signal_id'], ['ai_anomaly_signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recommendation_anomaly', 'ai_recommendations', ['anomaly_signal_id'], unique=False)
    op.create_index('idx_recommendation_created', 'ai_recommendations', ['created_at'], unique=False)
    op.create_index('idx_recommendation_status', 'ai_recommendations', ['hitl_status'], unique=False)
    op.create_table('ai_human_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recommendation_id', sa.String(length=36), nullable=False),
    sa.Column('decided_by', sa.String(length=255), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('edited_action', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.CheckConstraint("decision IN ('approve','reject','edit')", name='ck_human_decision_value'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['ai_recommendations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_human_decision_decided_at', 'ai_human_decisions', ['decided_at'], unique=False)
    op.create_index('idx_human_decision_recommendation', 'ai_human_decisions', ['recommendation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_human_decision_recommendation', table_name='ai_human_decisions')
    op.drop_index('idx_human_decision_decided_at', table_name='ai_human_decisions')
    op.drop_table('ai_human_decisions')
    op.drop_index('idx_recommendation_status', table_name='ai_recommendations')
    op.drop_index('idx_recommendation_created', table_name='ai_recommendations')
    op.drop_index('idx_recommendation_anomaly', table_name='ai_recommendations')
    op.drop_table('ai_recommendations')
    op.drop_index('idx_worker_run_worker_status', table_name='ai_worker_runs')
    op.drop_index('idx_worker_run_started', table_name='ai_worker_runs')
    op.drop_table('ai_worker_runs')
    op.drop_table('ai_daily_briefs')
    op.drop_index('idx_anomaly_status', table_name='ai_anomaly_signals')
    op.drop_index('idx_anomaly_scope', table_name='ai_anomaly_signals')
    op.drop_index('idx_anomaly_detected_at', table_name='ai_anomaly_signals')
    op.drop_table('ai_anomaly_signals')
    # ### end Alembic commands ###
