"""0002 pii vault records

Revision ID: bb688fa367e5
Revises: 3a1bc4fecef2
Create Date: 2026-05-09 04:59:41.785362
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'bb688fa367e5'
down_revision: str | None = '3a1bc4fecef2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pii_vault_records',
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('value_ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('value_iv', sa.LargeBinary(), nullable=False),
    sa.Column('key_version', sa.SmallInteger(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usage_count', sa.BigInteger(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("category IN ('cpf','cns','name','email','phone','address')", name='ck_pii_vault_category'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index('idx_pii_category', 'pii_vault_records', ['category'], unique=False)
    op.create_index('idx_pii_expires_at', 'pii_vault_records', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_pii_expires_at', table_name='pii_vault_records')
    op.drop_index('idx_pii_category', table_name='pii_vault_records')
    op.drop_table('pii_vault_records')
    # ### end Alembic commands ###
